<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    /** @var string  */
    protected $table = 'project';

    protected $fillable = [
        'name',
        'description'
    ];

    public function save(array $options = [])
    {
        $userId = request()->user()->id;
        $
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
