<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Project
 * @package App
 * @property integer $user_id
 */
class Project extends Model
{
    /** @var string */
    protected $table = 'project';

    protected $fillable = [
        'name',
        'description'
    ];

    public function save(array $options = [])
    {
        $userId = request()->user()->id;

        $this->user_id = $userId;
        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function photos()
    {
        $this->hasMany(Photo::class);
    }
}
